// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr3Xeykf2GLbS5UlsKy93hC9_OZSzuo7Q',
    appId: '1:878855395264:web:8e5309216dc81b12f31a25',
    messagingSenderId: '878855395264',
    projectId: 'smart-factory-b3dce',
    authDomain: 'smart-factory-b3dce.firebaseapp.com',
    storageBucket: 'smart-factory-b3dce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4RkrKDDN09je0sZA7kYulwV9cOigA5A',
    appId: '1:878855395264:android:e41931dcd9a627acf31a25',
    messagingSenderId: '878855395264',
    projectId: 'smart-factory-b3dce',
    storageBucket: 'smart-factory-b3dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIb19hY00Ohd9tjrAsL9LjRhA-jyg3oPk',
    appId: '1:878855395264:ios:47575d6075df628bf31a25',
    messagingSenderId: '878855395264',
    projectId: 'smart-factory-b3dce',
    storageBucket: 'smart-factory-b3dce.appspot.com',
    iosClientId: '878855395264-4bvbiusbbn05lecvstvbebv17hu81l22.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
